version: '3.8'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

##
#  docker exec -it <IMAGE NAME / ID> bash
#
#  kafka-console-producer --topic <TOPIC_NAME> --bootstrap-server localhost:9092
#  kafka-console-consumer --topic <TOPIC_NAME> --from-beginning --bootstrap-server localhost:9092
#
#  kafka-topics --list --bootstrap-server localhost:9092
#  kafka-topics --create --topic <TOPIC_NAME> --partitions 3 --replication-factor 1 --bootstrap-server localhost:9092
#  kafka-topics --describe --topic <TOPIC_NAME> --bootstrap-server localhost:9092
#  kafka-topics --delete --topic <TOPIC_NAME> --bootstrap-server localhost:9092
#
#  kafka-consumer-groups --bootstrap-server localhost:9092 --list
#
